# Generated by Django 5.0.3 on 2024-03-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer_lvl', models.CharField(choices=[('1A', 'summer'), ('2A', 'spring'), ('3A', 'autumn'), ('4A', 'winter')], default=None, max_length=2)),
                ('spring_lvl', models.CharField(choices=[('1A', 'summer'), ('2A', 'spring'), ('3A', 'autumn'), ('4A', 'winter')], default=None, max_length=2)),
                ('autumn_lvl', models.CharField(choices=[('1A', 'summer'), ('2A', 'spring'), ('3A', 'autumn'), ('4A', 'winter')], default=None, max_length=2)),
                ('winter_lvl', models.CharField(choices=[('1A', 'summer'), ('2A', 'spring'), ('3A', 'autumn'), ('4A', 'winter')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('other_titles', models.CharField(max_length=128)),
                ('connect', models.CharField(max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NW', 'new'), ('PG', 'pending'), ('AC', 'accepted'), ('RJ', 'rejected')], default='NW', max_length=2)),
                ('coords_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mountain.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain.level')),
                ('turist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=64)),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountain.pereval')),
            ],
        ),
    ]
