# Generated by Django 5.0.3 on 2024-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='turist_id',
            new_name='tourist_id',
        ),
    ]
